project:
  type: website
  output-dir: docs

website:
  title: "Ринок ШСД"
  navbar:
    left:
      - href: index.qmd
        text: Дашборд
      - Аналіз.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

